# Generated by Django 2.0.3 on 2018-03-26 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voipartner', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Status_Contrato',
        ),
    ]
