# Generated by Django 2.0.3 on 2018-04-07 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voipartner', '0002_delete_status_contrato'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrato',
            name='comprovante_deposito',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='contrato',
            name='contrato_assinado',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='contrato',
            name='link_contrato',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contrato',
            name='log_mudanca_status',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='status',
            field=models.CharField(choices=[('1', 'pagamento pendente'), ('2', 'aguardando compensação'), ('3', 'aguardando assinatura do contrato'), ('4', 'contrato em vigor')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='email',
            field=models.EmailField(max_length=100, null=True),
        ),
    ]
