# Generated by Django 2.0.3 on 2018-04-09 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voipartner', '0004_contrato_detalhamento_resgate'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='upload_documento_identificacao',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
